version: '3.8'

services:
  # Definición del Microservicio de Dominio: Catálogo (Implementación en Golang).
  # Este servicio actúa como la fuente de verdad para la información de productos.
  catalog-api:
    build:
      # Definición del contexto de construcción (Build Context) aislado.
      # Asegura que el demonio de Docker solo tenga acceso a los archivos necesarios para este servicio.
      context: ./services/catalog-api
      dockerfile: Dockerfile
    ports:
      # Publicación de puertos (Port Binding) para acceso externo.
      # Exposición directa del puerto de servicio al host.
      - "8080:8080"
    environment:
      # Inyección de configuración en tiempo de ejecución (Runtime Configuration).
      - PORT=8080

  # Definición del Microservicio de Dominio: Pedidos (Implementación en .NET 8).
  # Gestiona el ciclo de vida transaccional de las órdenes de compra.
  orders-api:
    build:
      context: ./services/orders-api
      dockerfile: Dockerfile
    ports:
      # Estrategia de mapeo de puertos para evitar colisiones en el Host.
      # Se mapea el puerto interno estándar del contenedor (8080) a un puerto distinto en el Host (5000),
      # permitiendo la ejecución paralela de múltiples servicios que escuchan internamente en el mismo puerto.
      - "5000:8080"
    environment:
      # Configuración del servidor Kestrel para realizar el binding en todas las interfaces de red (0.0.0.0)
      # dentro del contenedor, garantizando la accesibilidad desde la red de Docker.
      - ASPNETCORE_URLS=http://+:8080
